apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kong.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kong.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kong.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kong
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/kong.yaml
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
            - name: KONG_PLUGINS
              value: "bundled,custom"
            - name: KONG_LUA_PACKAGE_PATH
              value: "/kong/plugins/?.lua;;"
            - name: USER_SERVICE_HOST
              value: "{{ .Values.env.userServiceHost }}"
            - name: USER_SERVICE_PORT
              value: "{{ .Values.env.userServicePort | quote }}"
            - name: JWT_SECRET
              value: "{{ .Values.env.jwtSecret }}"
            - name: ALLOWED_CIDR
              value: "{{ .Values.env.allowedCidr }}"
          ports:
            - name: proxy
              containerPort: 8000
            - name: proxy-ssl
              containerPort: 8443
            - name: admin
              containerPort: 8001
          volumeMounts:
            - name: kong-config
              mountPath: /kong/kong.yaml
              subPath: kong.yaml
            - name: kong-plugin
              mountPath: /kong/plugins/custom.lua
              subPath: custom.lua
{{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: kong-config
          configMap:
            name: {{ include "kong.fullname" . }}-config
        - name: kong-plugin
          configMap:
            name: {{ include "kong.fullname" . }}-plugin