apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kong.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kong.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8000
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 8443
      protocol: TCP

